### PR TITLE
Update the Status of this Document to be more in line with other W3C documents.

### PR DESCRIPTION
**Pull request by hober**
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/17.html" title="Last updated on Jul 28, 2021, 4:16 PM UTC (a3d9358)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/17/4f5a63c...a3d9358.html" title="Last updated on Jul 28, 2021, 4:16 PM UTC (a3d9358)">Diff</a>

### CODE REVIEW

**Comment by ylafon** [comment]
Note that only the TAG can publish findings, the beginning of the text might imply that TFs and other groups than the TAG may publish those.

**Review by ylafon — APPROVED** [review]

**Review by wseltzer — APPROVED** [review]

**Review by jyasskin — APPROVED** [review]
My only strong feeling here is that this keep saying that this document isn't yet the consensus of the task force, and you've kept that, so LGTM. :)

**Comment by torgo** [comment]
Pending update from @hober.

**Comment by hober** [comment]
> Pending update from @hober.

Updated. Should I go ahead and merge this now?

**Review by jyasskin — APPROVED** [review]

**Pull request merged**
