### PR TITLE
Remove the endorsement of exchanging personal data for content.

### PR DESCRIPTION
**Pull request by jyasskin**
This reverts #436 and commit 254a8d0dbf553563c5b9f7c01d4cc606a5ce6851. Some folks on the TAG objected to the change.

***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/451.html" title="Last updated on Nov 14, 2024, 6:30 PM UTC (10afc18)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/451/48e1a5f...jyasskin:10afc18.html" title="Last updated on Nov 14, 2024, 6:30 PM UTC (10afc18)">Diff</a>

### CODE REVIEW

**Review by martinthomson — APPROVED** [review]

**Review by hober — APPROVED** [review]
I'm not sure if simply removing the text is the best approach, but I don't have alternative text to suggest. I can live with this change.

**Comment by thegreatfatzby** [comment]
Hey @jyasskin I haven't been able to participate in this forum as much as I'd like so sorry if this is me wandering in out of my element...is the object to this language a) that it belongs somewhere but just not here (like maybe it belongs in a Private Advertising Tech group but not the Privacy <no modifier> Group) or b) a more foundational objection?

**Review by torgo — APPROVED** [review]
yes. re-reviewing this I'm not sure how this got in here in the first place. :/

**Comment by dmarti** [comment]
@torgo This was a modified version of a general suggestion from the formal objection ( https://github.com/w3ctag/privacy-principles/issues/431 https://github.com/w3ctag/privacy-principles/pull/436 ) 

I tried to split out the really problematic case (where the power relationship between the user and the site does not allow for a meaningful choice to share data) from the case that is more like a subscription or paid download, but at a price of zero.

**Comment by jyasskin** [comment]
@thegreatfatzby If I understand it correctly, it's a more foundational objection, wondering whether data access is so abusable that it should never be a valid thing to trade for access. I think we might be able to agree on _something_ on this topic in a future version of this document, and if the objector wants to insist on this, the Council could always agree to reinstate this wording. As you suggest, it might be productive for an advertising group to propose the next iteration of wording, with an argument that the privacy impacts are reasonable.

Seeing general consensus from the TAG, and remembering the sense that the task force would probably not have added this if I hadn't argued in favor of it, I'm going to merge this.

**Pull request merged**
