### PR TITLE
Remove some sarcasm about FIPs.

### PR DESCRIPTION
**Pull request by jyasskin**
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/234.html" title="Last updated on Mar 23, 2023, 12:19 AM UTC (024d562)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/234/d759205...jyasskin:024d562.html" title="Last updated on Mar 23, 2023, 12:19 AM UTC (024d562)">Diff</a>

### CODE REVIEW

**Comment by jyasskin** [comment]
I'm not sure we should be spending so much space on the FIPs, but at least this line should be more direct.

**Comment by darobin** [comment]
FWIW I disagree with this change. I don't think that our docs are improved by making them blander and more technocratic. They're more effective when they're written by people for people.

We're spending time on the FIPs because that's perhaps the most common mistake made?

**Comment by chrisn** [comment]
I'm currently reading through the draft, now that TAG has invited wider review. This is one of the items in my notes to comment on. This change looks good, or at least use the past tense in that sentence.

**Review by hober — APPROVED** [review]
Looks good to me.

**Pull request merged**
