### PR TITLE
Add Singling Out and Profiling to the high level threats.

### LINKED ISSUE #27: Privacy principles by category (high level privacy threats)
Consider adding:

- **Single-Out:** The ability to single out an individual from a population or group of individuals.
- **Profiling:** The processing of data to infer, evaluate or predict an individual's attributes, interests or behaviours.

Consider expanding **Stored Data Compromise** to **Data Compromise**, i.e. systems that do not take adequate measures to secure data from unauthorised or inappropriate access.

### PR DESCRIPTION
**Pull request by jyasskin**
Also broaden Data Compromise to include non-stored data.

Fixes #27.

We might instead want to modify Correlation and Identification to include these
threats.

***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/37.html#principles" title="Last updated on Sep 1, 2021, 5:12 PM UTC (0c3fccc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/37/9bf9bae...jyasskin:0c3fccc.html" title="Last updated on Sep 1, 2021, 5:12 PM UTC (0c3fccc)">Diff</a>

### CODE REVIEW

**Review by sandandsnow — COMMENTED** [review]
@jyasskin looks good to me

**Comment by jyasskin** [comment]
Sorry for not getting back to this before you looked at it again, @sandandsnow. It now incorporates the [discussion from last week](https://github.com/w3ctag/privacy-principles/blob/main/meetings/2021-08-25-minutes.md#add-singling-out-and-profiling-to-the-high-level-threats) by merging singling-out back into a wider meaning for identification.

**Comment by samuelweiler** [comment]
replace individual with person. 

Maybe add some distinction between "browser profile" and "profiling".

**Comment by jyasskin** [comment]
I'll replace "individual" with "person" in a subsequent PR. The other changes we mentioned on today's call are now done. I'll leave this for a day to get any other comments, and then merge.

**Pull request merged**
